services:
  - type: web
    name: be-notify-receiver
    runtime: node
    plan: starter
    region: singapore
    rootDir: server/notify-receiver
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /healthz
