export type AuthorityPermission = {
  permission_key: string;
  permission_group: string;
  label_en: string;
  label_my: string;
};

export const authorityPermissions: AuthorityPermission[] = [
  { permission_key: "accounting_account_balance_download", permission_group: "Accounting", label_en: "Accounting account balance download", label_my: "စာရင်းကိုင် account balance download" },
  { permission_key: "accounting_account_balance_read", permission_group: "Accounting", label_en: "Accounting account balance read", label_my: "စာရင်းကိုင် account balance ဖတ်ရှုရန်" },
  { permission_key: "accounting_account_create", permission_group: "Accounting", label_en: "Accounting account create", label_my: "စာရင်းကိုင် account ဖန်တီးရန်" },
  { permission_key: "accounting_account_delete", permission_group: "Accounting", label_en: "Accounting account delete", label_my: "စာရင်းကိုင် account ဖျက်ရန်" },
  { permission_key: "accounting_account_list", permission_group: "Accounting", label_en: "Accounting account list", label_my: "စာရင်းကိုင် account စာရင်း" },
  { permission_key: "accounting_account_update", permission_group: "Accounting", label_en: "Accounting account update", label_my: "စာရင်းကိုင် account ပြင်ဆင်ရန်" },
  { permission_key: "accounting_balance_sheet_download", permission_group: "Accounting", label_en: "Accounting balance sheet download", label_my: "Balance sheet download" },
  { permission_key: "accounting_balance_sheet_read", permission_group: "Accounting", label_en: "Accounting balance sheet read", label_my: "Balance sheet ဖတ်ရှုရန်" },
  { permission_key: "accounting_daily_accounting_download", permission_group: "Accounting", label_en: "Accounting daily accounting download", label_my: "Daily accounting download" },
  { permission_key: "accounting_daily_accounting_read", permission_group: "Accounting", label_en: "Accounting daily accounting read", label_my: "Daily accounting ဖတ်ရှုရန်" },
  { permission_key: "accounting_income_statement_download", permission_group: "Accounting", label_en: "Accounting income statement download", label_my: "Income statement download" },
  { permission_key: "accounting_income_statement_read", permission_group: "Accounting", label_en: "Accounting income statement read", label_my: "Income statement ဖတ်ရှုရန်" },
  { permission_key: "accounting_journal_summary_download", permission_group: "Accounting", label_en: "Accounting journal summary download", label_my: "Journal summary download" },
  { permission_key: "accounting_journal_summary_read", permission_group: "Accounting", label_en: "Accounting journal summary read", label_my: "Journal summary ဖတ်ရှုရန်" },
  { permission_key: "accounting_journal_voucher_list_download", permission_group: "Accounting", label_en: "Accounting journal voucher list download", label_my: "Journal voucher list download" },
  { permission_key: "accounting_journal_voucher_create", permission_group: "Accounting", label_en: "Accounting journal voucher create", label_my: "Journal voucher ဖန်တီးရန်" },
  { permission_key: "accounting_journal_voucher_list", permission_group: "Accounting", label_en: "Accounting journal voucher list", label_my: "Journal voucher စာရင်း" },
  { permission_key: "accounting_ledger_list", permission_group: "Accounting", label_en: "Accounting ledger list", label_my: "Ledger စာရင်း" },
  { permission_key: "accounting_ledger_list_download", permission_group: "Accounting", label_en: "Accounting ledger list download", label_my: "Ledger list download" },
  { permission_key: "accounting_profit_and_loss_download", permission_group: "Accounting", label_en: "Accounting profit and loss download", label_my: "Profit and loss download" },
  { permission_key: "accounting_profit_and_loss_read", permission_group: "Accounting", label_en: "Accounting profit and loss read", label_my: "Profit and loss ဖတ်ရှုရန်" },
  { permission_key: "accounting_simple_transaction_create", permission_group: "Accounting", label_en: "Accounting simple transaction create", label_my: "Simple transaction ဖန်တီးရန်" },
  { permission_key: "accounting_trial_balance_read", permission_group: "Accounting", label_en: "Accounting trial balance read", label_my: "Trial balance ဖတ်ရှုရန်" },
  { permission_key: "accounting_trial_balance_download", permission_group: "Accounting", label_en: "Accounting trial balance download", label_my: "Trial balance download" },

  { permission_key: "address_create", permission_group: "Address", label_en: "Address create", label_my: "လိပ်စာ ဖန်တီးရန်" },
  { permission_key: "address_delete", permission_group: "Address", label_en: "Address delete", label_my: "လိပ်စာ ဖျက်ရန်" },
  { permission_key: "address_read", permission_group: "Address", label_en: "Address read", label_my: "လိပ်စာ ဖတ်ရှုရန်" },
  { permission_key: "address_update", permission_group: "Address", label_en: "Address update", label_my: "လိပ်စာ ပြင်ဆင်ရန်" },

  { permission_key: "allow_pos_service", permission_group: "General", label_en: "Allow POS service", label_my: "POS service ခွင့်ပြုရန်" },
  { permission_key: "allow_received_from_pay_to_branch", permission_group: "General", label_en: "Allow received from / pay to branch", label_my: "Branch receive/pay ခွင့်ပြုရန်" },

  { permission_key: "chat_add_member", permission_group: "Chat", label_en: "Chat add member", label_my: "Chat member ထည့်ရန်" },
  { permission_key: "chat_group_rename", permission_group: "Chat", label_en: "Chat group rename", label_my: "Chat group အမည်ပြောင်းရန်" },
  { permission_key: "chat_message_delete", permission_group: "Chat", label_en: "Chat message delete", label_my: "Chat message ဖျက်ရန်" },
  { permission_key: "chat_message_read", permission_group: "Chat", label_en: "Chat message read", label_my: "Chat message ဖတ်ရှုရန်" },
  { permission_key: "chat_message_write", permission_group: "Chat", label_en: "Chat message write", label_my: "Chat message ရေးရန်" },
  { permission_key: "chat_remove_member", permission_group: "Chat", label_en: "Chat remove member", label_my: "Chat member ဖယ်ရန်" },
  { permission_key: "chat_search_people_and_groups", permission_group: "Chat", label_en: "Chat search people and groups", label_my: "Chat လူ/အဖွဲ့ ရှာရန်" },

  { permission_key: "comment_create", permission_group: "Comment", label_en: "Comment create", label_my: "Comment ဖန်တီးရန်" },
  { permission_key: "comment_delete", permission_group: "Comment", label_en: "Comment delete", label_my: "Comment ဖျက်ရန်" },
  { permission_key: "comment_read", permission_group: "Comment", label_en: "Comment read", label_my: "Comment ဖတ်ရှုရန်" },

  { permission_key: "deliver_accept", permission_group: "Deliver", label_en: "Deliver accept", label_my: "Deliver လက်ခံရန်" },
  { permission_key: "deliver_allow_price_update", permission_group: "Deliver", label_en: "Deliver allow price update", label_my: "Deliver စျေးနှုန်းပြင်ရန် ခွင့်ပြုရန်" },
  { permission_key: "deliver_allow_way_update", permission_group: "Deliver", label_en: "Deliver allow way update", label_my: "Deliver way ပြင်ရန် ခွင့်ပြုရန်" },
  { permission_key: "deliver_assign", permission_group: "Deliver", label_en: "Deliver assign", label_my: "Deliver တာဝန်ပေးရန်" },
  { permission_key: "deliver_cancel", permission_group: "Deliver", label_en: "Deliver cancel", label_my: "Deliver ပယ်ဖျက်ရန်" },
  { permission_key: "deliver_create_update", permission_group: "Deliver", label_en: "Deliver create/update", label_my: "Deliver ဖန်တီး/ပြင်ဆင်ရန်" },
  { permission_key: "deliver_delete", permission_group: "Deliver", label_en: "Deliver delete", label_my: "Deliver ဖျက်ရန်" },
  { permission_key: "deliver_management_level_read", permission_group: "Deliver", label_en: "Deliver management level read", label_my: "Deliver management level ဖတ်ရှုရန်" },
  { permission_key: "deliver_read", permission_group: "Deliver", label_en: "Deliver read", label_my: "Deliver ဖတ်ရှုရန်" },
  { permission_key: "deliver_visible_all_deliver_ways", permission_group: "Deliver", label_en: "Deliver visible all deliver ways", label_my: "Deliver ways အားလုံး မြင်နိုင်ရန်" },
  { permission_key: "deliver_way_allow_failed_to_deliver", permission_group: "Deliver", label_en: "Deliver way allow failed to deliver", label_my: "Failed to deliver ခွင့်ပြုရန်" },
  { permission_key: "deliver_way_allow_to_complete", permission_group: "Deliver", label_en: "Deliver way allow to complete", label_my: "Complete လုပ်ခွင့်" },
  { permission_key: "deliver_way_force_action", permission_group: "Deliver", label_en: "Deliver way force action", label_my: "Deliver way force action" },
  { permission_key: "deliver_way_processing", permission_group: "Deliver", label_en: "Deliver way processing", label_my: "Deliver way processing" },

  { permission_key: "department_create", permission_group: "Department", label_en: "Department create", label_my: "ဌာန ဖန်တီးရန်" },
  { permission_key: "department_delete", permission_group: "Department", label_en: "Department delete", label_my: "ဌာန ဖျက်ရန်" },
  { permission_key: "department_read", permission_group: "Department", label_en: "Department read", label_my: "ဌာန ဖတ်ရှုရန်" },
  { permission_key: "department_update", permission_group: "Department", label_en: "Department update", label_my: "ဌာန ပြင်ဆင်ရန်" },

  { permission_key: "finance_received_from_merchant_download", permission_group: "Finance", label_en: "Finance received from merchant download", label_my: "Merchant received list download" },
  { permission_key: "finance_received_from_merchant_list", permission_group: "Finance", label_en: "Finance received from merchant list", label_my: "Merchant received list" },
  { permission_key: "finance_pricing_delete", permission_group: "Finance", label_en: "Finance pricing delete", label_my: "Finance pricing ဖျက်ရန်" },
  { permission_key: "finance_cod_from_deliveryman_list", permission_group: "Finance", label_en: "Finance COD from deliveryman list", label_my: "COD from deliveryman list" },
  { permission_key: "finance_cod_from_deliveryman_list_download", permission_group: "Finance", label_en: "Finance COD from deliveryman list download", label_my: "COD list download" },
  { permission_key: "finance_cod_received_from_deliveryman", permission_group: "Finance", label_en: "Finance COD received from deliveryman", label_my: "COD received from deliveryman" },
  { permission_key: "finance_pricing_create", permission_group: "Finance", label_en: "Finance pricing create", label_my: "Finance pricing ဖန်တီးရန်" },
  { permission_key: "finance_pricing_exclusive_create", permission_group: "Finance", label_en: "Finance pricing exclusive create", label_my: "Exclusive pricing ဖန်တီးရန်" },
  { permission_key: "finance_pricing_exclusive_delete", permission_group: "Finance", label_en: "Finance pricing exclusive delete", label_my: "Exclusive pricing ဖျက်ရန်" },
  { permission_key: "finance_pricing_exclusive_list", permission_group: "Finance", label_en: "Finance pricing exclusive list", label_my: "Exclusive pricing list" },
  { permission_key: "finance_pricing_exclusive_update", permission_group: "Finance", label_en: "Finance pricing exclusive update", label_my: "Exclusive pricing ပြင်ရန်" },
  { permission_key: "finance_pricing_list", permission_group: "Finance", label_en: "Finance pricing list", label_my: "Finance pricing list" },
  { permission_key: "finance_pricing_read", permission_group: "Finance", label_en: "Finance pricing read", label_my: "Finance pricing ဖတ်ရှုရန်" },
  { permission_key: "finance_pricing_update", permission_group: "Finance", label_en: "Finance pricing update", label_my: "Finance pricing ပြင်ရန်" },
  { permission_key: "finance_received_from_merchant_create", permission_group: "Finance", label_en: "Finance received from merchant create", label_my: "Received from merchant ဖန်တီးရန်" },
  { permission_key: "finance_refund_to_merchant_create", permission_group: "Finance", label_en: "Finance refund to merchant create", label_my: "Refund to merchant ဖန်တီးရန်" },
  { permission_key: "finance_refund_to_merchant_list", permission_group: "Finance", label_en: "Finance refund to merchant list", label_my: "Refund to merchant list" },
  { permission_key: "finance_refund_to_merchant_list_download", permission_group: "Finance", label_en: "Finance refund to merchant list download", label_my: "Refund list download" },
  { permission_key: "finance_visible_all_deliver_ways", permission_group: "Finance", label_en: "Finance visible all deliver ways", label_my: "Deliver ways အားလုံး မြင်နိုင်ရန်" },
  { permission_key: "finance_visible_all_pickup_ways", permission_group: "Finance", label_en: "Finance visible all pickup ways", label_my: "Pickup ways အားလုံး မြင်နိုင်ရန်" },

  { permission_key: "logs_read", permission_group: "Logs", label_en: "Logs read", label_my: "Logs ဖတ်ရှုရန်" },
  { permission_key: "notification_delete", permission_group: "Notification", label_en: "Notification delete", label_my: "Notification ဖျက်ရန်" },
  { permission_key: "notification_read", permission_group: "Notification", label_en: "Notification read", label_my: "Notification ဖတ်ရှုရန်" },

  { permission_key: "pickup_accept", permission_group: "Pickup", label_en: "Pickup accept", label_my: "Pickup လက်ခံရန်" },
  { permission_key: "pickup_assign", permission_group: "Pickup", label_en: "Pickup assign", label_my: "Pickup တာဝန်ပေးရန်" },
  { permission_key: "pickup_cancel", permission_group: "Pickup", label_en: "Pickup cancel", label_my: "Pickup ပယ်ဖျက်ရန်" },
  { permission_key: "pickup_create", permission_group: "Pickup", label_en: "Pickup create", label_my: "Pickup ဖန်တီးရန်" },
  { permission_key: "pickup_delete", permission_group: "Pickup", label_en: "Pickup delete", label_my: "Pickup ဖျက်ရန်" },
  { permission_key: "pickup_merchant_direct_order_read", permission_group: "Pickup", label_en: "Pickup merchant direct order read", label_my: "Merchant direct order ဖတ်ရှုရန်" },
  { permission_key: "pickup_read", permission_group: "Pickup", label_en: "Pickup read", label_my: "Pickup ဖတ်ရှုရန်" },
  { permission_key: "pickup_update", permission_group: "Pickup", label_en: "Pickup update", label_my: "Pickup ပြင်ဆင်ရန်" },
  { permission_key: "pickup_visible_all_pickup_ways", permission_group: "Pickup", label_en: "Pickup visible all pickup ways", label_my: "Pickup ways အားလုံး မြင်နိုင်ရန်" },
  { permission_key: "pickup_way_force_action", permission_group: "Pickup", label_en: "Pickup way force action", label_my: "Pickup way force action" },
  { permission_key: "pickup_way_processing", permission_group: "Pickup", label_en: "Pickup way processing", label_my: "Pickup way processing" },

  { permission_key: "promotion_cashback_create", permission_group: "Promotion", label_en: "Promotion cashback create", label_my: "Cashback promotion ဖန်တီးရန်" },
  { permission_key: "promotion_cashback_generate_reports", permission_group: "Promotion", label_en: "Promotion cashback generate reports", label_my: "Cashback report ထုတ်ရန်" },
  { permission_key: "promotion_cashback_list", permission_group: "Promotion", label_en: "Promotion cashback list", label_my: "Cashback list" },
  { permission_key: "promotion_cashback_list_report_download", permission_group: "Promotion", label_en: "Promotion cashback list report download", label_my: "Cashback report download" },
  { permission_key: "promotion_cashback_list_reports", permission_group: "Promotion", label_en: "Promotion cashback list reports", label_my: "Cashback reports" },
  { permission_key: "promotion_cashback_update", permission_group: "Promotion", label_en: "Promotion cashback update", label_my: "Cashback update" },
  { permission_key: "promotion_code_check_validity", permission_group: "Promotion", label_en: "Promotion code check validity", label_my: "Promotion code validity စစ်ရန်" },
  { permission_key: "promotion_code_create", permission_group: "Promotion", label_en: "Promotion code create", label_my: "Promotion code ဖန်တီးရန်" },
  { permission_key: "promotion_code_list", permission_group: "Promotion", label_en: "Promotion code list", label_my: "Promotion code list" },
  { permission_key: "promotion_code_list_download", permission_group: "Promotion", label_en: "Promotion code list download", label_my: "Promotion code list download" },
  { permission_key: "promotion_create", permission_group: "Promotion", label_en: "Promotion create", label_my: "Promotion ဖန်တီးရန်" },
  { permission_key: "promotion_delete", permission_group: "Promotion", label_en: "Promotion delete", label_my: "Promotion ဖျက်ရန်" },
  { permission_key: "promotion_list", permission_group: "Promotion", label_en: "Promotion list", label_my: "Promotion list" },
  { permission_key: "promotion_read", permission_group: "Promotion", label_en: "Promotion read", label_my: "Promotion ဖတ်ရှုရန်" },
  { permission_key: "promotion_update", permission_group: "Promotion", label_en: "Promotion update", label_my: "Promotion ပြင်ဆင်ရန်" },

  { permission_key: "setting_global_create", permission_group: "Setting", label_en: "Setting global create", label_my: "Global setting ဖန်တီးရန်" },
  { permission_key: "setting_global_delete", permission_group: "Setting", label_en: "Setting global delete", label_my: "Global setting ဖျက်ရန်" },
  { permission_key: "setting_global_read", permission_group: "Setting", label_en: "Setting global read", label_my: "Global setting ဖတ်ရှုရန်" },
  { permission_key: "setting_global_update", permission_group: "Setting", label_en: "Setting global update", label_my: "Global setting ပြင်ရန်" },
  { permission_key: "setting_local_create", permission_group: "Setting", label_en: "Setting local create", label_my: "Local setting ဖန်တီးရန်" },
  { permission_key: "setting_local_delete", permission_group: "Setting", label_en: "Setting local delete", label_my: "Local setting ဖျက်ရန်" },
  { permission_key: "setting_local_read", permission_group: "Setting", label_en: "Setting local read", label_my: "Local setting ဖတ်ရှုရန်" },
  { permission_key: "setting_local_update", permission_group: "Setting", label_en: "Setting local update", label_my: "Local setting ပြင်ရန်" },

  { permission_key: "station_bucket_create", permission_group: "Station", label_en: "Station bucket create", label_my: "Station bucket ဖန်တီးရန်" },
  { permission_key: "station_bucket_delete", permission_group: "Station", label_en: "Station bucket delete", label_my: "Station bucket ဖျက်ရန်" },
  { permission_key: "station_bucket_list", permission_group: "Station", label_en: "Station bucket list", label_my: "Station bucket list" },
  { permission_key: "station_bucket_update", permission_group: "Station", label_en: "Station bucket update", label_my: "Station bucket ပြင်ရန်" },
  { permission_key: "station_create", permission_group: "Station", label_en: "Station create", label_my: "Station ဖန်တီးရန်" },
  { permission_key: "station_inbound_list", permission_group: "Station", label_en: "Station inbound list", label_my: "Inbound list" },
  { permission_key: "station_list", permission_group: "Station", label_en: "Station list", label_my: "Station list" },
  { permission_key: "station_outbound_list", permission_group: "Station", label_en: "Station outbound list", label_my: "Outbound list" },
  { permission_key: "station_read", permission_group: "Station", label_en: "Station read", label_my: "Station ဖတ်ရှုရန်" },
  { permission_key: "station_schedule_create", permission_group: "Station", label_en: "Station schedule create", label_my: "Station schedule ဖန်တီးရန်" },
  { permission_key: "station_schedule_delete", permission_group: "Station", label_en: "Station schedule delete", label_my: "Station schedule ဖျက်ရန်" },
  { permission_key: "station_schedule_list", permission_group: "Station", label_en: "Station schedule list", label_my: "Station schedule list" },
  { permission_key: "station_schedule_update", permission_group: "Station", label_en: "Station schedule update", label_my: "Station schedule ပြင်ရန်" },
  { permission_key: "station_update", permission_group: "Station", label_en: "Station update", label_my: "Station ပြင်ရန်" },

  { permission_key: "user_account_create", permission_group: "User", label_en: "User account create", label_my: "User account ဖန်တီးရန်" },
  { permission_key: "user_account_deliveryman_list", permission_group: "User", label_en: "User account deliveryman list", label_my: "Deliveryman account list" },
  { permission_key: "user_account_merchant_list", permission_group: "User", label_en: "User account merchant list", label_my: "Merchant account list" },
  { permission_key: "user_account_sync_to_hr_management", permission_group: "User", label_en: "User account Sync to HR Management", label_my: "HR sync ခွင့်ပြုရန်" },
  { permission_key: "user_deliveryman_account_create", permission_group: "User", label_en: "User deliveryman account create", label_my: "Deliveryman account ဖန်တီးရန်" },
  { permission_key: "user_merchant_account_create", permission_group: "User", label_en: "User merchant account create", label_my: "Merchant account ဖန်တီးရန်" },
  { permission_key: "user_role_change", permission_group: "User", label_en: "User role change", label_my: "User role ပြောင်းရန်" },
  { permission_key: "user_role_create", permission_group: "User", label_en: "User role create", label_my: "Role ဖန်တီးရန်" },
  { permission_key: "user_role_list_by_privileges", permission_group: "User", label_en: "User role list by privileges", label_my: "Privileges အလိုက် role list" },
  { permission_key: "user_role_update", permission_group: "User", label_en: "User role update", label_my: "Role ပြင်ရန်" },
  { permission_key: "user_track_the_deliverymen", permission_group: "User", label_en: "User track the deliverymen", label_my: "Deliverymen ကို track လုပ်ရန်" },
  { permission_key: "user_visible_all_deliverymen", permission_group: "User", label_en: "User visible all deliverymen", label_my: "Deliverymen အားလုံး မြင်နိုင်ရန်" },
  { permission_key: "user_visible_all_merchants", permission_group: "User", label_en: "User visible all merchants", label_my: "Merchants အားလုံး မြင်နိုင်ရန်" },

  { permission_key: "zone_create", permission_group: "Zone", label_en: "Zone create", label_my: "Zone ဖန်တီးရန်" },
  { permission_key: "zone_delete", permission_group: "Zone", label_en: "Zone delete", label_my: "Zone ဖျက်ရန်" },
  { permission_key: "zone_list", permission_group: "Zone", label_en: "Zone list", label_my: "Zone list" },
  { permission_key: "zone_read", permission_group: "Zone", label_en: "Zone read", label_my: "Zone ဖတ်ရှုရန်" },
  { permission_key: "zone_update", permission_group: "Zone", label_en: "Zone update", label_my: "Zone ပြင်ရန်" }
];
